[package]
name = "iamgroot"
version = "0.0.0"
edition = "2021"
description = "TBD"
license = "MIT"

[dependencies]

# Dependencies necessary for generated code to build
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1.17"
regex = "1.7"
