// NOTE: This will be provided as the only necessary compile-time dependency.
pub mod jsonrpc;

// Code generated by the tool based on the OpenRPC spec.
pub mod generated;

// User-defined implementation of a generated `gen::Rpc` trait.
pub mod implemented;
