// NOTE: This will be provided as the only necessary compile-time dependency.
mod jsonrpc;

// Code generated by the tool based on the OpenRPC spec.
mod generated;

// User-defined implementation of a generated `gen::Rpc` trait.
mod implemented;

fn main() {
    println!("It works!");
}
